config/routes.rb
Rails.application.routes.draw do
resources :workers
resources :welcome
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  get "posts/new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/worker.rb
class Worker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    # def new
    #     @post = Post.new
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: %i[ show edit update destroy ]

  # GET /workers or /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1 or /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers or /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to worker_url(@worker), notice: "Worker was successfully created." }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1 or /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to worker_url(@worker), notice: "Worker was successfully updated." }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1 or /workers/1.json
  def destroy
    @worker.destroy

    respond_to do |format|
      format.html { redirect_to workers_url, notice: "Worker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worker_params
      params.require(:worker).permit(:nombre, :salario)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link type="stylesheet" href="app/assets/stylesheets/application.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" >WORKERS APP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="workers">CRUD</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="background">
    <%= yield %>
    </div>

    <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2023 - CRUD2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<h1>Nuevo Post</h1>

# <%= form_for :post, url => {:action => create} do |f| %>
#     <p>

app/views/welcome/index.html.erb
<h1 class="" style="text-align:center;">My Administration APP</h1>

<div style="text-align:center;">
<%= link_to image_tag('admin.jpg') %>
</div>

app/views/workers/_form.html.erb
<%= form_with(model: worker) do |form| %>
  <% if worker.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
        <% worker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :salario, style: "display: block" %>
    <%= form.text_field :salario %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/workers/_worker.html.erb
<div id="<%= dom_id worker %>">
  <p>
    <strong>Nombre:</strong>
    <%= worker.nombre %>
  </p>

  <p>
    <strong>Salario:</strong>
    <%= worker.salario %>
  </p>

</div>

app/views/workers/edit.html.erb
<h1>Editing worker</h1>

<%= render "form", worker: @worker %>

<br>

<div>
  <%= link_to "Show this worker", @worker %> |
  <%= link_to "Back to workers", workers_path %>
</div>

app/views/workers/index.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

<p style="color: green"><%= notice %></p>

<h1 style="text-align:center">Workers</h1>

<div  id="workers">
  <% @workers.each do |worker| %>
    <%= render worker %>
    
    <p>
      <%= link_to "Show this worker", worker %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "New worker", new_worker_path %>

app/views/workers/new.html.erb
<div style="text-align:center">
  <h1>New worker</h1>

  <%= render "form", worker: @worker %>

  <br>

  <div>
    <%= link_to "Back to workers", workers_path %>
  </div>
</div>

app/views/workers/show.html.erb
<div style="text-align:center">
  <p style="color: green"><%= notice %></p>

  <%= render @worker %>

  <div>
    <%= link_to "Edit this worker", edit_worker_path(@worker) %> |
    <%= link_to "Back to workers", workers_path %>

    <%= button_to "Destroy this worker", @worker, method: :delete %>
  </div>
</div>